// <auto-generated />
namespace Application.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MsgtoApplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MsgtoApplication));
        
        string IMigrationMetadata.Id
        {
            get { return "202406081754291_Msg to Application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
