// <auto-generated />
namespace Application.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rolestring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rolestring));
        
        string IMigrationMetadata.Id
        {
            get { return "202406092038194_role string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
