// <auto-generated />
namespace Application.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CV_updaasdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CV_updaasdf));
        
        string IMigrationMetadata.Id
        {
            get { return "202405222151276_CV_updaasdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
